### ISSUE TITLE
Skipping Session Steps

### ISSUE THREAD

**Issue by phrankie** [sparors/laravel-ussd#12]
How do I skip through ussd session steps?
Example:
My Ussd Code is *500#

But I would like to go directly to the second step of my session journey by dialling
*500*1*3#

**Comment by CyberSai** [comment]
Usually the first input of USSD are the short code the user dialed. Instead of setting an initial State, you can use an Action Instead.
In the Action, you check the user input, and based on the value, you return the state you want to show to the user.
Eg.
```
// in your controller use an action as the initial state
$ussd = Ussd::machine()->setInitialState(InitialAction::class);
```
```
// in your initial action
class InitialAction extends Action
{
    public function run(): string
    {
        $input = $this->record->get('input'); // where you save user input in record

        if ('*3*4#' == $input) { // the short code to jump
            return NextState::class;
        }

        return WelcomeState::class; // default starting point
    }
}
```

**Comment by phrankie** [comment]
Thank you for the response, Makes a lot of sense. Awesome work with this package.

**Comment by CyberSai** [comment]
Thank you.
