### ISSUE TITLE
Http POST Request not working

### ISSUE THREAD

**Issue by owususamuel** [sparors/laravel-ussd#18]
Operator's both requests and repose come as Http POST.
Changing the route to post method breaks the code.

**Comment by yawmanford** [comment]
@owususamuel In laravel, you can exclude your HTTP post URLs from CSRF verification in this file, VerifyCsrfToken.php

Example:

```
/**
 * The URIs that should be excluded from CSRF verification.
 *
 * @var array
 */
protected $except = [
    'ussd',
    'callback',
];
```
