### ISSUE TITLE
How to show a prompt without input field

### ISSUE THREAD

**Issue by owususamuel** [sparors/laravel-ussd#22]
How do I show a prompt that shows no input field?

**Comment by owususamuel** [comment]
And how to end the user session

**Comment by CyberSai** [comment]
Hello @owususamuel you can find the documentation here https://sparors.github.io/ussd-docs/docs/state/

You just need to override the action property like so

```php
namespace App\Http\Ussd\States;

use Sparors\Ussd\State;

class MyState extends State
{
    protected $action = self::PROMPT; // This show prompt and end session

    protected function beforeRendering(): void
    {
        //
    }

    protected function afterRendering(string $argument): void
    {
        //
    }
}
```

Although it depends on your operator, please read their documentation to know how to translate the response correctly.


Here are some examples
- https://github.com/yawmanford/ussd-africastalking-example
- https://github.com/yawmanford/ussd-nsano-example
- https://github.com/yawmanford/ussd-hubtel-example

**Comment by CyberSai** [comment]
Since this is not an issue, I will go ahead and close it. Thank you.
