### ISSUE TITLE
How to save states screen into database with Eloquent ???

### ISSUE THREAD

**Issue by chegmarco1989** [sparors/laravel-ussd#30]
Hi.

Is there any way to save states (USSD screens) into database ??? Because Laravel USSD Sparors's States is not Contrôler.

If so, How to do it ???
In other words, How to save USSD MENUS into Database After creating migrations ???

Please inform us.

**Comment by papamarfo** [comment]
Hi, 

What is your use case for saving the menus in the database? 

By default, all states are handled for you automatically.
