### ISSUE TITLE
How do i access the Record Object of a particular Machine Session

### ISSUE THREAD

**Issue by kwekubright** [sparors/laravel-ussd#31]
Hi guys 👋 ,
I have recently fallen in love ❤️ with this project. Thank you for your work.
 
I would love to know how to retrieve data saved in record for a particular machine session. 
After the user interacts with my application i would like to be able to access the data saved in record from another class which is neither a State or Action class. 

Below is how my code looks like in my route
```
Route::any('/test', function (Request $request) {
    $ussd = Ussd::machine()
        ->setSessionId($request->Mobile)
        ->setInitialState(\App\Http\Ussd\States\Home::class)
        ->setNetworkFromRequest('Operator')
        ->setPhoneNumberFromRequest('Mobile')
        ->setInput(request()->input('Type') == env('USSD_INITIAL_TYPE') ? env('BEINSURED_DEFAULT_MSG') : $request->Message)
        ->setResponse(function (string $message) {
            return [
                'Message' => $message,
                'Type' => session()->get('ussd.type') !== 'Release' ? 'Response' : 'Release',
                "MaskNextRoute" => true,
            ];
        })
        ->setStore('redis');

    return response()->json($ussd->run());
});
```

How do i achieve this 🙏

**Comment by papamarfo** [comment]
Hi @kwekubright,

thanks for reaching out. Please refer to the **Retrieve Data** section from the URL below. Also for best practice in Laravel, use **config()** to retrieve environmental variables instead of **env()**.

URL: https://sparors.github.io/ussd-docs/docs/record/

**Comment by papamarfo** [comment]
To access the data saved in the record from another class which is neither a State nor Action class, since you are using Laravel, you can retrieve data from the database from your models or DB facade.

**Comment by kwekubright** [comment]
Thanks for your reply @papamarfo 
The method for retrieving data according to the url provided will only work in state or actions right?

How can I retrieve data outside a state or action class.?

**Comment by papamarfo** [comment]
Correct. If the data is stored in the database, you can use a model or DB facade.
