### ISSUE TITLE
Feature Request: Resume session

### ISSUE THREAD

**Issue by Parables** [sparors/laravel-ussd#33]
A USSD session may be timed out or may end abruptly without a user completing a flow.

In my use case, we have a user fill out a form, we tried to limit the number of inputs so that the user can complete the session in one go. 

But not every user is fast enough to respond to these prompts especially those on feature phones(torchlight + radio only). These people always suffer timed-out sessions because they switch the input method and the typical press 1-3 or more times to input a single letter.

I manually implemented a buggy solution which involved using:
1. a middleware to intercept the request to decide whether the previous session is still valid(not expired)
2. using a separate cache to store the compound key of the phone_number and session
3. an event listener and handler which fires when the cache is written to. It checks the key of the write operation. Keys with certain prefixes like `__preserved__` are stored permanently
4. The middleware checks and attempts to reconstruct the previous session(if it exists), populate the record with the previous data, determines the last complete state, modifies the `__init__` and `__active__` keys and finally displays a state which prompts the user to resume from the last step or start a fresh session

This implementation was so buggy and hacky(messing with internal records etc).

A cleaner, baked-in, easy-to-opt-in solution will be a great feature to have.

A much simpler approach is to let provide something like a State Machine config.This will allow the USSD machine to know where to resume automatically.  See [Spatie's Laravel Model state](https://github.com/spatie/laravel-model-states)  for inspiration

Please do consider this issue ... I'm ready to share further details as needed though I may not be able to send a PR at the moment because I spend less time behind my computer these days.

**Comment by papamarfo** [comment]
Hi @Parables,

Thanks for the suggestion. This feature will be added and released in v3.0.0

**Comment by Parables** [comment]
Why closed as completed when it hasn't been implemented.

Please reopen the issue until the feature has been added, tested and released before closing it as complete.
