### ISSUE TITLE
Resume timed-out USSD sessions

### ISSUE THREAD

**Issue by mkojoa** [sparors/laravel-ussd#37]
I have an issue with my sessions to time out mostly, can you share trick on how to resume-timed-out USSD sessions? I have a session where user input full names and address, tin numbers ,etc.
Secondary it seems the script took longtime to respond sometimes,I do not know whether is my hosting issue or script itself or internet connection!
Regards

**Comment by papamarfo** [comment]
Hi @mkojoa,

Sorry for the delay. You can find this feature in v3.0. Below is a link

https://github.com/sparors/laravel-ussd/tree/3.x
